package: mediapool_exif
version: '2.1.2'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/mediapool_exif

console_commands:
    mediapool_exif:read: '\FriendsOfRedaxo\addon\MediapoolExif\Cli\Read'


requires:
    packages:
        mediapool: '>=2.13.0'
        metainfo: '>=2.10.0'
    redaxo: ^5.15.0
    php:
        version: '>=8.1'
        extensions: [exif]
