package: mediapool_exif
version: '1.1.0-beta'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/mediapool_exif

console_commands:
    mediapool_exif:read: '\FriendsOfRedaxo\addon\MediapoolExif\Cli\Read'


requires:
    packages:
        mediapool: '>=2.3.0'
    redaxo: ^5.2.0
    php:
        version: '>=7.1'
        extensions: [exif]
